---
- name: deploy app server
  hosts: DB
  vars:
    repo: https://github.com/mbaran0v/python-sample-app.git
    app_path: /app
  become: yes
  roles:
    - Install_Role
    - DB_Role
  tasks:
    - name: create dir for project
      file:
        path: "{{ app_path }}"
        state: directory
    - name: clone project
      git:
        repo: "{{ repo }}"
        dest: "{{ app_path }}"
