---
- name: Install packages for Debian
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-pip
    - python-dev
    - libpq-dev
    - python-all
- name: Install package
  shell:
    pip install psycopg2