---
# tasks file for DB_Role
- name: check linux family
  debug: var=ansible_os_family
- import_tasks: debian_pack.yml
  when: ansible_os_family == 'Debian'
- import_tasks: rh_pack.yml
  when: ansible_os_family == 'RedHat'

- name: create db
    shell: |
      sudo -u postgres psql template1
      create role worker superuser login createdb createrole password 'root';
      create database thesis with owner root;
      /q





#- name: create db
#  become: true
#  become_user: postgres
#  postgresql_db:
#    name: app
#- name: create user
#  become: true
#  become_user: postgres
#  postgresql_user:
#    db: app
#    name: worker
#    password: "worker"
    


