---
# tasks file for DB_Role
- name: check linux family
  debug: var=ansible_os_family
- import_tasks: debian_pack.yml
  when: ansible_os_family == 'Debian'
- import_tasks: rh_pack.yml
  when: ansible_os_family == 'RedHat'

- name: create user
  postgresql_user:
    name: worker
    password: "worker"
  become_user: postgres
- name: create DB
  postgresql_db:
    name: app
    owner: worker
  become_user: postgres

    


