---
- name: Add PostgreSQL YUM Repository
  shell:
    yum install -y https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
- name: install postgresql
  yum:
    name: postgresql11-server
    state: present
